[package]
name = "image-cache-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
redis = { version = "0.22", features = ["tokio-comp"] }
image = "0.24"
lazy_static = "1.4"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"